version: 2.1

references:
  .working_directory: &working_directory /tmp/workspace/explorer-desktop
  #                                                     ~~~~~~~~~~~~~~~~ <- repo name

  .working_directory_root: &working_directory_root
    working_directory: *working_directory

  .attach_root: &attach_root
    attach_workspace:
      at: *working_directory

  .unity_linux_image: &unity_linux_image
    - image: unityci/editor:ubuntu-2020.3.0f1-linux-il2cpp-0.12.0
      environment:
        DCL_OUTPUT_NAME: linux
        PROJECT_PATH: /tmp/workspace/explorer-desktop/unity-renderer-desktop
        BUILD_TARGET: StandaloneLinux64
        BUILD_NAME: unity-renderer-linux
        BUILD_PATH: /tmp/workspace/explorer-desktop/Builds/unity-renderer-linux/
        #                          ~~~~~~~~~~~~~~~~ <- repo name
        #                                                  ~~~~~~~~~~~~~~~~~~~~ <- folder name

  .unity_mac_image: &unity_mac_image
    - image: unityci/editor:ubuntu-2020.3.0f1-mac-mono-0.12.0
      environment:
        DCL_OUTPUT_NAME: mac
        PROJECT_PATH: /tmp/workspace/explorer-desktop/unity-renderer-desktop
        BUILD_TARGET: StandaloneOSX
        BUILD_NAME: unity-renderer-mac
        BUILD_PATH: /tmp/workspace/explorer-desktop/Builds/unity-renderer-mac/
        #                          ~~~~~~~~~~~~~~~~ <- repo name
        #                                                  ~~~~~~~~~~~~~~~~~~ <- folder name

  .unity_windows_image: &unity_windows_image
    - image: unityci/editor:ubuntu-2020.3.0f1-windows-mono-0.12.0
      environment:
        DCL_OUTPUT_NAME: windows
        PROJECT_PATH: /tmp/workspace/explorer-desktop/unity-renderer-desktop
        BUILD_TARGET: StandaloneWindows64
        BUILD_NAME: unity-renderer-windows
        BUILD_PATH: /tmp/workspace/explorer-desktop/Builds/unity-renderer-windows/
        #                          ~~~~~~~~~~~~~~~~ <- repo name
        #                                                  ~~~~~~~~~~~~~~~~~~~~~~ <- folder name

  .cached_paths: &CACHED_PATHS
    - ./unity-renderer-desktop/test-results
    - ./unity-renderer-desktop/editmode-logs.txt
    - ./unity-renderer-desktop/playmode-logs.txt
    - ./unity-renderer-desktop/build-logs.txt
    - ./unity-renderer-desktop/ab-logs.txt
    - ./unity-renderer-desktop/playmode-results.xml
    - ./unity-renderer-desktop/CodeCoverage
    - ./unity-renderer-desktop/TestResources/VisualTests
    - ./unity-renderer-desktop/Builds/

  .all_branches_and_tags: &all_branches_and_tags
    filters:
      branches:
        only: /(.*)/
      tags:
        only: /^\d+\.\d+\.\d+(.*)/ # npm tag + latest

commands:
  build-unity-generic:
    steps:
      - run:
          name: Prepare image
          command: |
            apt-get update
            apt-get install -y zip jq
      - run:
          name: Local unity-renderer
          command: |
            ./download-unity-renderer-repo.sh
      - run:
          name: Build Unity Project
          no_output_timeout: 30m
          command: |
            if [[ ! -e ${BUILD_PATH} ]] || [[ ! -e "${BUILD_PATH}/build-logs.txt" ]] || [[ ! -n "$(ls -A ${BUILD_PATH})" ]]; then
                mkdir -p ${BUILD_PATH}

                ./ci-build.sh
            else
              echo "Skipping build, using cached artifacts."
            fi;
      - run:
          name: Print build logs
          command: cat ${BUILD_PATH}/build-logs.txt
          when: always

      # persist to workspace to use in downstream jobs
      - persist_to_workspace:
          root: *working_directory
          paths:
            - Builds
      - run:
          name: Check there are build artifacts
          command: |
            if [ -z "$(ls -A "${BUILD_PATH}")" ]; then
              echo "directory ${BUILD_PATH}/Builds is empty"
              exit 1
            fi
      - run:
          environment:
            ARTIFACT_PATH: /tmp/workspace/explorer-desktop/unity-desktop-artifacts/
          name: Compress artifacts
          command: |
            mkdir -p unity-desktop-artifacts
            cd ${BUILD_PATH}
            zip -r unity-renderer-${DCL_OUTPUT_NAME}.zip ./
            mv unity-renderer-${DCL_OUTPUT_NAME}.zip ${ARTIFACT_PATH}
      - persist_to_workspace:
          root: *working_directory
          paths:
            - ./unity-desktop-artifacts/
      - run:
          name: Print all files (in failure)
          when: on_fail
          command: |
            find "${BUILD_PATH}"

jobs:
  checkout:
    <<: *working_directory_root
    docker:
      - image: cimg/base:2021.04
    steps:
      - run:
          name: Prepare image
          command: |
            sudo apt-get update
            sudo apt-get install -y jq
      - checkout

      # persist to workspace to use in downstream jobs
      - persist_to_workspace:
          root: *working_directory
          paths:
            - "*"
  build-unity-for-linux:
    <<: *working_directory_root
    resource_class: xlarge
    docker: *unity_linux_image
    steps:
      - <<: *attach_root
      - build-unity-generic
  build-unity-for-windows:
    <<: *working_directory_root
    resource_class: xlarge
    docker: *unity_windows_image
    steps:
      - <<: *attach_root
      - build-unity-generic
  build-unity-for-mac:
    <<: *working_directory_root
    resource_class: xlarge
    docker: *unity_mac_image
    steps:
      - <<: *attach_root
      - build-unity-generic
  playmode-tests:
    <<: *working_directory_root
    resource_class: xlarge
    docker: *unity_windows_image
    steps:
      - <<: *attach_root
      - run: &HASH_UNITY_FILES
          name: Get the hash of source files
          command: |
            # hash unity files
            find ./unity-renderer-desktop -type f \( -not -path '*Library*' \) \( -not -path '*browser-interface*' \) \( -iname \*.unity -o -iname \*.sh -o -iname \*.cs -o -iname \*.meta -o -iname \*.xml -o -iname \*.shader -o -iname \*.prefab -o -iname \*.yml -o -iname \*.mat -o -iname \*.json -o -iname \*.js -o -iname \*.jspre  -o -iname \*.jslib  -o -iname \*.hlsl  -o -iname \*.asmdef  -o -iname \*.csproj  -o -iname \*.spriteatlas  -o -iname \*.asset  \) \( -exec md5sum "$PWD"/{} \; \) | sort > ../.unitysources-checksum
            # hash pipeline files
            find ./ -type f \( -iname \*.sh -o -iname \*.yml \) \( -exec md5sum "$PWD"/{} \; \) | sort >> ../.unitysources-checksum
      - restore_cache:
          name: Restore hashed files if they exist
          keys:
            - unity-playmode-2020-3-{{ checksum "../.unitysources-checksum" }}
      - restore_cache: &RESTORE_LIBRARY_CACHE
          name: Restore library if exists
          keys:
            - library-2020-3-{{ .Branch }}
      - run:
          name: Prepare image
          command: |
            apt-get update
            apt-get install -y zip jq
      - run:
          name: Local unity-renderer
          command: |
            ./download-unity-renderer-repo.sh
      - run:
          name: Run playmode tests
          command: |
            if [[ -e ./unity-renderer-desktop/playmode-logs.txt ]]; then
                echo "Skipping playmode tests"
                exit 0
            else
                bash ci-playmode-test.sh
                exit $?
            fi;
          no_output_timeout: 30m
      - run:
          name: nunit-to-junit
          when: always
          command: |
            apt-get update
            apt-get install -y xsltproc
            xsltproc --output unity-renderer-desktop/test-results/playmode-results-junit.xml nunit-to-junit.xsl unity-renderer-desktop/playmode-results.xml
      - run: DEBIAN_FRONTEND=noninteractive apt-get -y -qq install awscli
      - run:
          name: upload code coverage
          command: |
            aws s3 sync /tmp/workspace/explorer-desktop/unity-renderer-desktop/CodeCoverage/Report "s3://${S3_BUCKET}/desktop-coverage/${CIRCLE_BRANCH}" --acl public-read
      - store_test_results:
          path: ./unity-renderer-desktop/test-results
      - store_artifacts:
          name: Store logs
          path: ./unity-renderer-desktop/playmode-logs.txt
      - store_artifacts:
          name: Store test results
          path: ./unity-renderer-desktop/playmode-results.xml
      - save_cache:
          name: Store test cache
          key: unity-playmode-2020-3-{{ checksum "../.unitysources-checksum" }}
          paths: *CACHED_PATHS
      - store_artifacts: &STORE_VISUAL_TESTS
          name: Store visual tests result as artifacts
          path: ./unity-renderer-desktop/TestResources/VisualTests
  publish-artifacts:
    <<: *working_directory_root
    docker:
      - image: cimg/base:2021.04
    steps:
      - <<: *attach_root
      - run:
          name: Prepare image
          command: |
            sudo apt-get update
            sudo apt-get -y -qq install awscli
      - run:
          name: Upload artifacts
          command: |
            ./ci/publish-artifacts.sh
workflows:
  version: 2
  build-deploy:
    jobs:
      - checkout:
          <<: *all_branches_and_tags

      - build-unity-for-linux:
          <<: *all_branches_and_tags
          requires:
            - checkout

      - build-unity-for-windows:
          <<: *all_branches_and_tags
          requires:
            - checkout

      - build-unity-for-mac:
          <<: *all_branches_and_tags
          requires:
            - checkout

      - playmode-tests:
          <<: *all_branches_and_tags
          requires:
            - checkout

      - publish-artifacts:
          <<: *all_branches_and_tags
          requires:
            - build-unity-for-linux
            - build-unity-for-windows
            - build-unity-for-mac
