name: Deploy release

on:
  check_run: 
    types: [ completed ]

jobs:
  deploy:
    if: ${{ github.event.check_run.name == 'CircleCI Checks' && github.event.check_run.conclusion == 'success' && github.event.check_run.app.name == 'build-deploy' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hmarr/debug-action@v2
      - name: Download artifacts
        run: |
          curl -o unity-renderer-windows.zip https://renderer-artifacts.decentraland.org/desktop/main/unity-renderer-windows.zip
          curl -o unity-renderer-mac.zip https://renderer-artifacts.decentraland.org/desktop/main/unity-renderer-mac.zip
          curl -o unity-renderer-linux.zip https://renderer-artifacts.decentraland.org/desktop/main/unity-renderer-linux.zip
      - name: Prepare release
        run: |
          zip unity-renderer.zip unity-renderer-windows.zip unity-renderer-mac.zip unity-renderer-linux.zip
      - name: Set version
        shell: bash
        run: |
          COMMIT_HASH=${{ github.sha }}
          DATE=$(date '+%Y%m%d%H%M%S')
          VERSION=1.0.${{github.run_number}}-${DATE}.commit-${COMMIT_HASH::7}
          echo ${VERSION}
          echo "##[set-output name=number;]$(echo ${VERSION})"
        id: set_version
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.set_version.outputs.number }}
          files: |
            unity-renderer.zip
      - name: Trigger pipeline
        run: |
          export PACKAGE_NAME="@dcl/explorer-desktop"
          curl \
            --request POST \
            --form token=${{ secrets.GITLAB_CDN_DEPLOYER_TOKEN }} \
            --form ref=master \
            --form-string variables[PACKAGE_NAME]="@dcl/explorer-desktop" \
            --form variables[PACKAGE_VERSION]=${{ steps.set_version.outputs.number }} \
            --form variables[REPO]=explorer-desktop \
            --form variables[REPO_OWNER]=decentraland \
            --form variables[COMMIT]=${{ github.sha }} \
            --form variables[GITHUB_RELEASE_ARTIFACT]=unity-renderer.zip \
            "${{ secrets.GITLAB_CDN_DEPLOYER_URL }}"