name: Deployment Notification

on:
  pull_request:
    types: [ opened ]

jobs:
  deployment_notification:
    runs-on: ubuntu-latest
    name: Decentraland Unity-Renderer Deployment Notification
    steps:
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@master
        with:
          message: |
            After the CI passes:

            This branch can be downloaded with the following instructions:
            ### For Windows:
              Execute the following commands in `Windows PowerShell`
              ```
                # Download
                curl -o unity-renderer-windows.zip https://renderer-artifacts.decentraland.org/desktop/${{ github.head_ref }}/unity-renderer-windows.zip

                # Unzip
                Expand-Archive -Path unity-renderer-windows.zip -DestinationPath unity-renderer-windows -Force
              ```
            ### For Mac:
              Execute the following commands:
              ```
              # Download
              curl -o unity-renderer-mac.zip https://renderer-artifacts.decentraland.org/desktop/${{ github.head_ref }}/unity-renderer-mac.zip

              # Unzip
              unzip unity-renderer-mac.zip -d unity-renderer-mac
              ```
            ### For Linux: 
              Execute the following commands:
              ```
              # Download
              curl -o unity-renderer-linux.zip https://renderer-artifacts.decentraland.org/desktop/${{ github.head_ref }}/unity-renderer-linux.zip

              # Unzip
              unzip unity-renderer-linux.zip -d unity-renderer-linux
              ```

          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
