name: Upload branch list

on: [create, delete, push]

jobs:
  update-branch-list:
    runs-on: ubuntu-latest
    name: Update Branch List to S3
    steps:
      - name: Get branch list
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          INPUT=$(git ls-remote --heads https://decentraland:${GITHUB_TOKEN}@github.com/decentraland/explorer-desktop.git)
          SUBSTRING=$(echo $INPUT | sed -e 's/[a-f0-9]\{40\} refs\/heads\///g')
          ARRAY=($SUBSTRING)
          mkdir -p branches/
          printf '%s\n' "${ARRAY[@]}" | jq -R . | jq -s . > branches/branches.json
      - name: Upload branch list artifacts
        env:
          AWS_DEFAULT_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          npx @dcl/cdn-uploader@next --bucket ${{ secrets.S3_BUCKET }} --local-folder branches --bucket-folder "desktop"